program Manejo;

uses
  Forms,
  Windows,
  Messages,
  SysUtils,
  Dialogs,
  UPai in 'UPai.pas' {FPai},
  Funcoes in 'Funcoes.pas',
  UConfiguracoes in 'UConfiguracoes.pas' {FConfiguracoes},
  UMensagens in 'UMensagens.pas',
  UMenu in 'UMenu.pas' {FMenu},
  USobre in 'USobre.pas' {FSobre},
  USplash in 'USplash.pas' {FSplash},
  UFasesCriacao in 'UFasesCriacao.pas' {FFasesCriacao},
  UVacinasMedicamentos in 'UVacinasMedicamentos.pas' {FVacinasMedicamentos},
  URacao in 'URacao.pas' {FRacao},
  UTipoRacao in 'UTipoRacao.pas' {FTipoRacao},
  UMetodoVacinasMedicamentos in 'UMetodoVacinasMedicamentos.pas' {FMetodoVacinasMedicamentos},
  UPadrao in 'UPadrao.pas' {FPadrao},
  ULinhagem in 'ULinhagem.pas' {FLinhagem},
  UOcorrencias in 'UOcorrencias.pas' {FOcorrencias},
  ULaboratorios in 'ULaboratorios.pas' {FLaboratorios},
  UFatorAvaliacao in 'UFatorAvaliacao.pas' {FFatorAvaliacao},
  UDetalhesRacao in 'UDetalhesRacao.pas' {FDetalhesRacao},
  URegistroTemperatura in 'URegistroTemperatura.pas' {FMovimentoRegistroTemperatura},
  UAlojamentoAves in 'UAlojamentoAves.pas' {FAlojamentoAves},
  UAlojamentoProducao in 'UAlojamentoProducao.pas' {FAlojamentoProducao},
  UEncerrarPadroes in 'UEncerrarPadroes.pas' {FEncerrarPadroes},
  UAgrupamentoLotes in 'UAgrupamentoLotes.pas' {FAgrupamentoLotes},
  UProgramacaoAtividades in 'UProgramacaoAtividades.pas' {FProgramacaoAtividades},
  UConfirmaDataMedia in 'UConfirmaDataMedia.pas' {FConfirmaDataMedia},
  UAvaliacaoTecnica in 'UAvaliacaoTecnica.pas' {FAvaliacaoTecnica},
  UIdentificacao in 'UIdentificacao.pas' {FIdentificacao},
  ULotes in 'ULotes.pas' {FLotes},
  UPerdas in 'UPerdas.pas' {FPerdas},
  UFaltaEnergia in 'UFaltaEnergia.pas' {FMovimentoFaltaEnergia},
  UTesteLote in 'UTesteLote.pas' {FMovimentoTesteLote},
  UUsoVacinas in 'UUsoVacinas.pas' {FMovimentoUsoVacinas},
  UPesagem in 'UPesagem.pas' {FPesagem},
  UDescarteFinal in 'UDescarteFinal.pas' {FMovimentoDescarteFinal},
  UMudancaEndereco in 'UMudancaEndereco.pas' {FMovimentoMudancaEndereco},
  UUsoMedicamentos in 'UUsoMedicamentos.pas' {FMovimentoUsoMedicamentos},
  UTransferenciaAves in 'UTransferenciaAves.pas' {FMovimentoTransferenciaAves},
  UFaltaAgua in 'UFaltaAgua.pas' {FMovimentoFaltaAgua},
  UProducaoOvos in 'UProducaoOvos.pas' {FMovimentoProducaoOvos},
  UPulorose in 'UPulorose.pas' {FMovimentoPulorose},
  UProgramacaoManejo in 'UProgramacaoManejo.pas' {FProgramacaoManejo},
  UDebicagem in 'UDebicagem.pas' {FMovimentoDebicagem},
  UComplementarIdades in 'UComplementarIdades.pas' {FComplementarIdades},
  UPesoEspecifico in 'UPesoEspecifico.pas' {FPesoEspecifico},
  UEntradaRacao in 'UEntradaRacao.pas' {FMovimentoEntradaRacao},
  USistemaArracoamento in 'USistemaArracoamento.pas' {FSistemaArracoamento},
  UCriarPadrao in 'UCriarPadrao.pas' {FCriarPadrao},
  UDesvincularLote in 'UDesvincularLote.pas' {FDesvincularLote},
  UCompletarGalpao in 'UCompletarGalpao.pas' {FCompletarGalpao},
  UAcertoSaldo in 'UAcertoSaldo.pas' {FAcertoSaldo},
  UResponsavelMovimentos in 'UResponsavelMovimentos.pas' {FReponsavelMovimentos},
  UDistribuicaoBox in 'UDistribuicaoBox.pas' {FDistribuicaoBox},
  UBox in 'UBox.pas' {FBox},
  USaldoNegativos in 'USaldoNegativos.pas' {FSaldoNegativos},
  UMonitorMovimentos in 'UMonitorMovimentos.pas' {FMonitorMovimentos},
  UCausas in 'UCausas.pas' {FCausa},
  UFechamentoSemanal in 'UFechamentoSemanal.pas' {FFechamentoSemanal},
  UFuncao in 'UFuncao.pas' {FFuncao},
  UResponsavel in 'UResponsavel.pas' {FResponsavel},
  USelecao in 'USelecao.pas' {FMovimentoSelecao},
  UVisVisualizador in 'UVisVisualizador.pas' {FVisVisualizador},
  UVisSelecionaImpressora in 'UVisSelecionaImpressora.pas' {FVisSelecionaImpressora},
  UVisProgressoPaginacao in 'UVisProgressoPaginacao.pas' {FVisProgressoPaginacao},
  URelatAnalProd in 'URelatAnalProd.pas' {FRelatAnalProd},
  URelatArracoamento in 'URelatArracoamento.pas' {FRelatArracoamento},
  URelatCriaRecria in 'URelatCriaRecria.pas' {FRelatCriaRecria},
  URelatPosicao in 'URelatPosicao.pas' {FRelatPosicao},
  uGrafDesempenhoVis in 'uGrafDesempenhoVis.pas' {FGrafDesempenhoVis},
  URelatFechamento in 'URelatFechamento.pas' {FRelatFechamento},
  URelatResumoPesagemProv in 'URelatResumoPesagemProv.pas' {FRelatResumoPesagemProv},
  URelatRelacao in 'URelatRelacao.pas' {FRelatRelacao},
  URelatPesagemProv in 'URelatPesagemProv.pas' {FRelatPesagemProv},
  URelatContProd in 'URelatContProd.pas' {FRelatContProd},
  UAcasalamento in 'UAcasalamento.pas' {FMovimentoAcasalamento},
  uGrafDesempenho in 'uGrafDesempenho.pas' {FGrafDesempenho},
  URelatDistribBox in 'URelatDistribBox.pas' {FRelatDistribBox},
  URelatContEstoque in 'URelatContEstoque.pas' {FRelatContEstoque},
  UGrupoAvaliacao in 'UGrupoAvaliacao.pas' {FGrupoAvaliacao},
  URelatSaldoAves in 'URelatSaldoAves.pas' {FRelatSaldoAves},
  USubGrupoAvaliacao in 'USubGrupoAvaliacao.pas' {FSubGrupoAvaliacao},
  URelatPlaAvaliacao in 'URelatPlaAvaliacao.pas' {FRelatPlaAvaliacao},
  UPlanilhaAvaliacao in 'UPlanilhaAvaliacao.pas' {frmPlanilhaAvaliacao},
  UConsumoRacao in 'UConsumoRacao.pas' {FMovimentoConsumoRacao},
  UEventos in 'UEventos.pas' {FEventos},
  UCadastroEvento in 'UCadastroEvento.pas' {FCadastroEventos},
  UArracoamentoSeparados in 'UArracoamentoSeparados.pas' {FArracoamentoSeparados},
  UArracoamentoAvos in 'UArracoamentoAvos.pas' {FArracoamentoAvos},
  UArracoamentoRecria in 'UArracoamentoRecria.pas' {FArracoamentoRecria},
  UArracoamentoJuntos in 'UArracoamentoJuntos.pas' {FArracoamentoJuntos},
  URelatDiario in 'URelatDiario.pas' {FRelatDiario},
  ULotesFormadores in 'ULotesFormadores.pas' {FLotesFormadores},
  URelatProdSemanal in 'URelatProdSemanal.pas' {FRelatProdSemanal},
  UConsultaProdRec in 'UConsultaProdRec.pas' {FProducaoRecebimento},
  URelatCompaDese in 'URelatCompaDese.pas' {FRelatCompaDese},
  UProgramaLuz in 'UProgramaLuz.pas' {FProgramaLuz},
  URelatAcompEclosao in 'URelatAcompEclosao.pas' {FRelatAcompEclosao},
  URelatAlojamentos in 'URelatAlojamentos.pas' {FRelatAlojamentos},
  URelatEstatistica in 'URelatEstatistica.pas' {FRelatEstatistica},
  UPesagemProv in 'UPesagemProv.pas' {FPesagemProv},
  URelatResumoPesagem in 'URelatResumoPesagem.pas' {FRelatResumoPesagem},
  uGrafMortalidade in 'uGrafMortalidade.pas' {FGrafMortalidade},
  uGrafMortalidadeVis in 'uGrafMortalidadeVis.pas' {FGrafMortalidadeVis},
  URelatDesempenho in 'URelatDesempenho.pas' {frmRelatPerformance},
  URelatSaldoPeso in 'URelatSaldoPeso.pas' {FRelatSaldoPeso},
  UFechamentoLote in 'UFechamentoLote.pas' {FFechamentoLote},
  UConsultaMovtoSemana in 'UConsultaMovtoSemana.pas' {FConsultaMovtoSemana},
  UClassificacaoOvos in 'UClassificacaoOvos.pas' {FClassificacaoOvos},
  URelatProgAtividades in 'URelatProgAtividades.pas' {FRelatProgAtividades},
  URelatAproveitamentoOvo in 'URelatAproveitamentoOvo.pas' {FRelatAproveitamentoOvo},
  URelatPesagem in 'URelatPesagem.pas' {FRelatPesagem},
  URelatFechamentoRecria in 'URelatFechamentoRecria.pas' {FRelatFechamentoRecria},
  URelatFechamentoRecriaF in 'URelatFechamentoRecriaF.pas' {FRelatFechamentoRecriaF},
  URelatFechamentoProdQ in 'URelatFechamentoProdQ.pas' {FRelatFechamentoProdQ},
  URelatFechamentoProdF in 'URelatFechamentoProdF.pas' {FRelatFechamentoProdF},
  URGerencialLote in 'URGerencialLote.pas' {FRGerencialLote},
  URGerencialLoteF in 'URGerencialLoteF.pas' {FRGerencialLoteF},
  UMovLote in 'UMovLote.pas' {FMovLote},
  URelatPesagemQRP in 'URelatPesagemQRP.pas' {FRelatPesagemQRP},
  URelatMortalidade in 'URelatMortalidade.pas' {FRelatMortalidade},
  URelatMortalidadeQRP in 'URelatMortalidadeQRP.pas' {FRelatMortalidadeQRP},
  UExpedicaoOvos in 'UExpedicaoOvos.pas' {FExpedicaoOvos},
  uRelatRomaneio in 'uRelatRomaneio.pas' {FRelatRomaneio},
  URelatRomaneioF in 'URelatRomaneioF.pas' {FRelatRomaneioF},
  UExpedicaoAves in 'UExpedicaoAves.pas' {FExpedicaoAves},
  UAcesso in 'UAcesso.pas' {FAcesso},
  URelatSaldo in 'URelatSaldo.pas' {FRelatSaldo},
  URelatSaldoQrp in 'URelatSaldoQrp.pas' {FRelatSaldoQrp},
  UParSaldoMatrizes in 'UParSaldoMatrizes.pas' {FParSaldoMatrizes},
  URelatCriticaProducao in 'URelatCriticaProducao.pas' {FRelatCriticaProducao},
  URelatCriticaProducaoQrp in 'URelatCriticaProducaoQrp.pas' {FRelatCriticaProducaoQrp},
  URelatRelacaoVacinas in 'URelatRelacaoVacinas.pas' {FRelatRelacaoVacinas},
  URelatRelacaoVacinasQ in 'URelatRelacaoVacinasQ.pas' {FRelatRelacaoVacinasQ},
  UEnviaProtheus in 'UEnviaProtheus.pas' {FEnviaProtheus},
  URelatAcompanhamentoMatrizes in 'URelatAcompanhamentoMatrizes.pas' {FRelatAcompanhamentoMatrizes},
  URelatAcompanhamentoMatrizesQ in 'URelatAcompanhamentoMatrizesQ.pas' {FRelatAcompanhamentoMatrizesQ},
  URelatAcompTecnicoMensal in 'URelatAcompTecnicoMensal.pas' {FRelatAcompTecnicoMensal},
  URelatAcompTecnicoMensalQ in 'URelatAcompTecnicoMensalQ.pas' {FRelatAcompTecnicoMensalQ},
  URelatAcompDiarioProducao in 'URelatAcompDiarioProducao.pas' {FRelatAcompDiarioProducao},
  URelatComparaRecria in 'URelatComparaRecria.pas' {FRelatComparaRecria},
  uRelatAnalProdQ2 in 'uRelatAnalProdQ2.pas' {FRelatAnalProdQ2},
  uRelatAcompDiarioProducaoQRP in 'uRelatAcompDiarioProducaoQRP.pas' {FRelatAcompDiarioProducaoQRP},
  uRelatSaldoAvesQRP in 'uRelatSaldoAvesQRP.pas' {FRelatSaldoAvesQRP},
  uRelRelacaoQRP in 'uRelRelacaoQRP.pas' {FRelRelacaoQRP},
  uRelatResumoPesagemQRP in 'uRelatResumoPesagemQRP.pas' {FRelatResumoPesagemQRP},
  uRelatContProdQRP in 'uRelatContProdQRP.pas' {FRelatContProdQRP},
  uRelatCriaRecriaQRP in 'uRelatCriaRecriaQRP.pas' {FRelatCriaRecriaQRP},
  uRelatComparaRecriaQRP in 'uRelatComparaRecriaQRP.pas' {FRelatComparaRecriaQRP},
  uRelatProdSemanalQRP in 'uRelatProdSemanalQRP.pas' {FRelatProdSemanalQRP},
  uRelatAproveitamentoOvoQ2 in 'uRelatAproveitamentoOvoQ2.pas' {FRelatAproveitamentoOvoQ2},
  uRelatAproveitamentoOvoQ3 in 'uRelatAproveitamentoOvoQ3.pas' {FRelatAproveitamentoOvoQ3},
  uRelatAproveitamentoOvoQ1 in 'uRelatAproveitamentoOvoQ1.pas' {FRelatAproveitamentoOvoQ1},
  uRelatPosicaoQRP in 'uRelatPosicaoQRP.pas' {FRelatPosicaoQRP},
  uRelatAnalProdQ in 'uRelatAnalProdQ.pas' {FRelatAnalProdQ},
  uRelatAnalProdQ3 in 'uRelatAnalProdQ3.pas' {FRelatAnalProdQ3},
  URelatLotesAlojQRP in 'URelatLotesAlojQRP.pas' {FRelatLotesAlojQRP},
  URelatProgramaVacinaF in 'URelatProgramaVacinaF.pas' {FRelatProgramaVacinaF},
  URelatProgramaVacinas in 'URelatProgramaVacinas.pas' {FRelatProgramaVacinas},
  URelatVendaAves in 'URelatVendaAves.pas' {FRelatVendaAves},
  URelatDesempOvoF in 'URelatDesempOvoF.pas' {FRelatDesempOvoF},
  uRelatArracoamentoRecria in 'uRelatArracoamentoRecria.pas' {FRelatArracoamentoRecria},
  URelatArracoamentoRecriaF in 'URelatArracoamentoRecriaF.pas' {FRelatArracoamentoRecriaF},
  URelatLotesAloj in 'URelatLotesAloj.pas' {FRelatLotesAloj};

var Hwnd : THandle;

{$R *.RES}

begin
  Hwnd:= FindWindow('TApplication', 'Manejo de Aves');
  if (Hwnd = 0) then {Se Hwnd <> 0, uma instância da aplicação já está aberta}
    begin
      FSplash := TFSplash.Create(Application);
      FSplash.Show;
      FSplash.Update;


      Application.Initialize;
      Application.Title := 'Manejo de Aves';
      Application.HelpFile := 'Manejo.hlp';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFConfiguracoes, FConfiguracoes);
  Application.CreateForm(TFDistribuicaoBox, FDistribuicaoBox);
  Application.CreateForm(TFRelatLotesAloj, FRelatLotesAloj);
  FSplash.Destroy;
      Application.Run;
    end
  else
    begin
      if not isWindowVisible(Hwnd) then
        begin
          PostMessage (Hwnd, wm_User, 0,0) ;
          ShowWindow(Hwnd, SW_MAXIMIZE);
        end;
      SetForegroundWindow(Hwnd);
    end;
end.
