SELECT * FROM avfscra1

/*CADASTRO LOTE*/
SELECT * FROM AVFSLOT1 where COD_LOTE_NUM=5188 --CADASTRO DE LOTE
SELECT * FROM AVFSALO1 WHERE COD_LOTE_NUM=5188 --ALOJAMENTO

/*MOVIMENTAÇÃO*/
SELECT * FROM AVFSMBO1 WHERE COD_LOTE_NUM=5188 --MOVIMENTAÇÃO
SELECT * FROM avfssda1 WHERE COD_LOTE_NUM=5188 --SALDO
SELECT * FROM AVFSMCR1 WHERE COD_LOTE_NUM=5188 --MOVIMENTO DE CONSUMO DE RAÇÃO

SELECT * FROM AVFSMPE1 WHERE COD_LOTE_NUM=5188 --PESAGEM


/*CADASTROS BÁSICOS*/
SELECT * FROM AVFSCAU1 --WHERE COD_LOTE_NUM=5188 --CAUSA
